// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BitCollectors.WinFormsControls.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// TestTextBoxExActionButton - Use 'TestTextBoxExActionButtonParams' to pass parameters into this method.
        /// </summary>
        public void TestTextBoxExActionButton()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIMainFormWindow.UIItemWindow.UIItemEdit;
            WinButton uIItemButton = this.UIMainFormWindow.UIItemWindow1.UIItemButton;
            #endregion

            // Type 'Test' in text box
            uIItemEdit.Text = this.TestTextBoxExActionButtonParams.UIItemEditText;

            // Click button
            Mouse.Click(uIItemButton, new Point(5, 9));
        }
        
        /// <summary>
        /// TestTextBoxExActionButtonAssertions - Use 'TestTextBoxExActionButtonAssertionsExpectedValues' to pass parameters into this method.
        /// </summary>
        public void TestTextBoxExActionButtonAssertions()
        {
            #region Variable Declarations
            WinEdit uIItemEdit = this.UIMainFormWindow.UIItemWindow.UIItemEdit;
            #endregion

            // Verify that the 'Text' property of text box equals 'Test'
            Assert.AreEqual(this.TestTextBoxExActionButtonAssertionsExpectedValues.UIItemEditText, uIItemEdit.Text, "TextBox should have the text \"Text\"");
        }
        
        #region Properties
        public virtual TestTextBoxExActionButtonParams TestTextBoxExActionButtonParams
        {
            get
            {
                if ((this.mTestTextBoxExActionButtonParams == null))
                {
                    this.mTestTextBoxExActionButtonParams = new TestTextBoxExActionButtonParams();
                }
                return this.mTestTextBoxExActionButtonParams;
            }
        }
        
        public virtual TestTextBoxExActionButtonAssertionsExpectedValues TestTextBoxExActionButtonAssertionsExpectedValues
        {
            get
            {
                if ((this.mTestTextBoxExActionButtonAssertionsExpectedValues == null))
                {
                    this.mTestTextBoxExActionButtonAssertionsExpectedValues = new TestTextBoxExActionButtonAssertionsExpectedValues();
                }
                return this.mTestTextBoxExActionButtonAssertionsExpectedValues;
            }
        }
        
        public UIMainFormWindow UIMainFormWindow
        {
            get
            {
                if ((this.mUIMainFormWindow == null))
                {
                    this.mUIMainFormWindow = new UIMainFormWindow();
                }
                return this.mUIMainFormWindow;
            }
        }
        #endregion
        
        #region Fields
        private TestTextBoxExActionButtonParams mTestTextBoxExActionButtonParams;
        
        private TestTextBoxExActionButtonAssertionsExpectedValues mTestTextBoxExActionButtonAssertionsExpectedValues;
        
        private UIMainFormWindow mUIMainFormWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestTextBoxExActionButton'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class TestTextBoxExActionButtonParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Test' in text box
        /// </summary>
        public string UIItemEditText = "Test";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'TestTextBoxExActionButtonAssertions'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class TestTextBoxExActionButtonAssertionsExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'Text' property of text box equals 'Test'
        /// </summary>
        public string UIItemEditText = "Test";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIMainFormWindow : WinWindow
    {
        
        public UIMainFormWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "MainForm";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainForm");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainForm");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIItemEdit.WindowTitles.Add("MainForm");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.30501.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainForm");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIItemButton.WindowTitles.Add("MainForm");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        #endregion
    }
}
